---
Name: version-history-routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'cms-version-history' : 'jonom\SilverStripe\VersionHistory\VersionHistoryController'
